tests:
### RIME stack test
  - name: net-udp
    timeout: 120
    devices:
      - name: receiver
        programdir: examples/inga-regression/net-tests-ip
        program: udp_ipv6_server
        instrument: []
        debug: []
        cflags: "-fno-inline -DAPP_SETTINGS_SET=1 -DCONF_DEST_NODE=$SENDER"
        graph_options: ""
      - name: sender
        programdir: examples/inga-regression/net-tests-ip
        program: udp_ipv6_client
        instrument: []
        debug: []
        cflags: "-fno-inline -DAPP_SETTINGS_SET=1 -DCONF_DEST_NODE=$RECEIVER"
        graph_options: ""
